- src/Clay.hs
- src/Clay/Render.hs
- src/Clay/Stylesheet.hs
this patch adds support for css `@import` statements. as far as i can see, clay doesn't have these at the moment (or at least doesn't have an obvious function for doing it)
> add support for importing css from urls

- src/Clay/Border.hs
- src/Clay/Display.hs
collapse conflicts with `Visibility` `collapse`
there are two bad ways: call `collapse` another word or add separate to `Visibility` and use it there
Since I can't imagine another intuitive name for collapse there is implementation with `borderCollapse :: Visibility -> Css`
> hacky support for `border-collapse` #88

- src/Clay/Stylesheet.hs
- src/Test.hs
#101
Could have targeted StyleM, but FlexibleInstances is used elsewhere and couldn't think of where it might be needed.  Changed the test as well.
> added Monoid instance for Css

- clay.cabal
It just works!
This test suite was disabled on hackage when fpco/stackage#768 was closed.
> Allow Hunit 1.3.*

- src/Clay/Pseudo.hs
- src/Clay/Render.hs
- src/Clay/Selector.hs
According to the [CSS3 standard](https://www.w3.org/TR/css3-selectors/#pseudo-elements), 
"Only one pseudo-element may appear per selector, and if present it must appear after the sequence of simple selectors that represents the subjects of the selector. "
But clay does not handle pseudo elements correctly.
for example:
```{.haskell}
TL.putStr . renderWith pretty [] $ (hover & (after & (C.width $ pct 100)))
```
result:
```
:after:hover
{
width : 100%;
}
```
this code is not appropreate because `:after` appears at the first of the selector.
With this fix, clay generates the following code.
```{.css}
:hover::after
{
width : 100%;
}
```
If there is some problem in this patch, let me know.
> Handle pseudo elements correctly

- src/Clay/Box.hs
Unless I'm missing something, there is currently no option for adding the spread radius to a box shadow. This should do it.
> Add boxShadowWithSpread function to Clay.Box to allow for spread radius.

- src/Clay/Border.hs
- src/Clay/Filter.hs
- src/Clay/Gradient.hs
- src/Clay/Media.hs
- src/Clay/Size.hs
- src/Clay/Transform.hs
CSS doesn't seem to differentiate between relative and absolute units. It does, however, differentiate between lengths and percentages. I'm basing this on [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/length). 
The way clay does sizes prevents users from specifying e.g. a border width of 1em. They also could specify opacity of 1em, which shouldn't be possible.
For this reason I replaced `Size Rel` and `Size Abs` with `Size Percentage` and `Size LengthUnit`. Do you think the naming is good?
I also changed [translate to allow usage of percentages](https://developer.mozilla.org/en-US/docs/Web/CSS/transform) for X and Y coordinates.
Also, the changes will not be really backwards comaptible, but the use cases which would work with CSS should also work after this change.
> Clean up units and percentages

- spec/Clay/RenderSpec.hs
- src/Clay/Render.hs
Fixes https://github.com/sebastiaanvisser/clay/issues/120
This PR extracts the `{` `}` opinion to fields in the Config type, and adds a new `htmlInline` config which avoids setting them.
NB. `inline` might be a better name, but it is already used by the `Display` module so I thought I'd avoid it.
> add htmlInline config

- spec/Clay/SizeSpec.hs
- src/Clay/Property.hs
- src/Clay/Size.hs
My shot at implementing the calc function for sizes in clay. There are a couple things which should be cleared up:
* The naming, I chose `@+@`, `@-@`, `@*`, `*@` and `@/`. Do you think it's understandable enough? Or should there be a specific calc function to make it more obvious what it is?
* The `Other` instance is done using a special alternative in the `Size` type.
* There are new GHC extensions used: `TypeFamilies` and `ExistentialQuantification`. Both of them make it easier to make everything more type safe, but maybe there's a way without them?
> Calc function for sizes

- clay.cabal
With nixpkgs 8bc0ece at the latest, the default hspec version is 2.4.1. Clay builds and passes the tests just fine with this version, so I've bumped the dependency in clay.cabal rather than jailbreaking the nix expression.
> bump hspec major version

- src/Clay/FontFace.hs
This is a small patch to add support for WOFF2 font format.
Cf https://www.w3.org/TR/WOFF2/
> Add WOFF2 font-face support

- CHANGELOG
- clay.cabal
- spec/Clay/RenderSpec.hs
- src/Clay.hs
- src/Clay/Comments.hs
- src/Clay/Render.hs
- src/Clay/Stylesheet.hs
This PR adds a new function `commenting` which annotates a value with a comment. For example,
```haskell
commenting :: CommentText -> Css -> Css
infixl 3 `commenting`
"A comment" `commenting` display displayNone
``` 
becomes
```css
{
display: none /* A comment */;
}
```
Only the `pretty` configuration is set to include comments by default.
The implementation means that if the supplied `Css` has multiple properties, all those in the top level will be annotated.
This does some of #149 (the relatively straightforward bit).
I'd be grateful to have this merged, if you are happy to do so, as soon as possible, as I'd like to use the new feature for updates to a downstream library (jgm/skylighting#27).
> Add `commenting` to annotate value with comment

- CHANGELOG
- spec/Clay/RenderSpec.hs
- src/Clay.hs
- src/Clay/Comments.hs
- src/Clay/Render.hs
- src/Clay/Stylesheet.hs
Use is very similar to `commenting`. This change actually touches all the areas that change did, and improves the implementation (specifically, the `Modifier` type makes the `Property` constructor far clearer).
Also includes test suite and changelog additions.
Fixes #107.
This does interact slightly with #158 so if you want to merge both, I'd be happy to rebase this, first.
> Add 'important' to annotate property with ‘important!

- CHANGELOG
- spec/Clay/BoxSpec.hs
- spec/Common.hs
- src/Clay/Box.hs
- src/Clay/Property.hs
Fixes #146 (also #144)
There is one breaking change (though the type error will make it obvious) to the type of `boxShadow`.
The rest of old API still available, though, with deprecation warnings.
-   `boxShadow` now takes a `NonEmpty` list of `BoxShadow` values.
-   Create `BoxShadow` values with the provided functions `shadow*`.
-   Modify using provided functions `bs*`.
Test suite + changelog included. The tests are a little noisy; there's probably an acceptable way to factor out all of the browser prefixes from the test results.
This does interact slightly with #158 and #159 so if you want to merge all three, I'd be happy to rebase this, first.
> Rewrite boxShadow functionality using BoxShadow newtype

- src/Clay/Pseudo.hs
- src/Clay/Selector.hs
The `:not()` pseudo selector now takes a `Selector` as argument, not a `Text`. This is closer to the CSS semantics and allows reuse of Clay selector syntax.
Note that this change will break the API and needs a bump. You can still just use string literals as arguments with OverloadedStrings, so the impact is likely very limited. 
Additionally I made a small fix in the selector parser by reusing the refinement parser internally. This means now things like `":first-child"` and `"@data-foo"` will parse properly. (using `with star` internally).
Not super relevant for now, but `PseudoFunc` is modelled to always take `Text` arguments, which is somewhat weakly typed and requires the `:not()` selector to convert to text immediately. Better model the actual function arguments types (e.g. `Text | …
> Not pseudo takes selector

- src/Clay/Transition.hs
Fixes #143 
It may not be worth deprecating `stepStop` since in its current form it doesn't actually work. If anyone is using it, then their CSS is broken.
> Fix stepStop to be stepEnd

- src/Clay/Size.hs
This allows uses like:
```haskell
sym2 padding (px 5) (pct 10)
```
where the units may differ by dimension.
> Relax types for `sym2` and `sym3` combinators

- spec/Clay/BoxSpec.hs
- spec/Clay/RenderSpec.hs
- spec/Common.hs
- src/Clay/Box.hs
- src/Clay/Color.hs
- src/Clay/Comments.hs
- src/Clay/Common.hs
- src/Clay/Display.hs
- src/Clay/FontFace.hs
- src/Clay/Gradient.hs
- src/Clay/List.hs
- src/Clay/Mask.hs
- src/Clay/Property.hs
- src/Clay/Render.hs
- src/Clay/Selector.hs
- src/Clay/Stylesheet.hs
- src/Clay/Text.hs
- src/Clay/Time.hs
- src/Clay/Transform.hs
- src/Clay/Transition.hs
This PR addresses #190. A few of the imports were actually unused, and have been removed. For the remaining imports, we now wrap them with CPP macros. **GHC 8.4.x** and later will now ignore these imports, avoiding the build noise. For **GHC 8.8.x**, any imports from `Monoid`, `Semigroup`, `Functor` and `Foldable` that were throwing warnings are now guarded by CPP macros.  I have tested these changes on **GHC 8.2.2**, **8.4.1**, **8.4.4**, **8.6.5** and **8.8.1**.
> Fix build warnings related to Monoid and Semigroup

- src/Clay.hs
- src/Clay/Render.hs
- src/Clay/Selector.hs
From https://developer.mozilla.org/en-US/docs/Web/CSS/General_sibling_selectors
> The ~ combinator separates two selectors and matches the second
> element only if it is preceded by the first, and both share a common
> parent.
> Add the "sibling" selector combinator

- examples/Main.hs
- examples/generate.sh
- src/Clay/Box.hs
- src/Clay/Color.hs
This closes #194.
Commit messages are self-explanatory. 2 things that are questionable are:
1) The way `Double`s are handled. Another option would be to make `s` and `m` of type `Integer`, but then other places would need to be fixed.
2) Usage of `fromList` instead of `OverloadedLists` option. The comment on top mentions the issue. If `OverloadedLists` is used, types in constructs like `forM_ [0..3] do ...` would need to be specified explicitly, which is not worth it in this example, since such constructs are used a lot.
The code has been tested on GHC 8.4.4, 8.6.5 and 8.8.1. Nix was not used for building, because I am not very familiar with it, and the example seems to not be included in .nix configuration files.
> Fixed example

- clay.cabal
- shell.nix
- src/Clay.hs
- src/Clay/Grid.hs
- src/Clay/Size.hs
Hi, I hit missing properties for sizes and grid areas and added them into my project. So, that it is draft for possible additions. I am not sure if experimental CSS API is acceptable in clay. Also, more consistent part of grid areas API should be added to the PR.
Use case:
``` CSS
.grid1 {
display: grid;
width: max-content;
}
.grid3 {
display: grid;
width: max-content;
}
@media (min-width: 40.0rem) {
.grid3 {
display: grid;
grid-template-columns: 1fr 1fr 1fr;
grid-gap: 1rem;
width: max-content;
}
}
```
``` haskell
".grid1" ? do
display grid
width maxContent
".grid3" ? do
display grid
width maxContent
query M.screen [M.minWidth (rem 40)] $ ".grid3" ? do
display grid
gridTemplateColumns [fr 1, fr 1, fr 1]
gridGap $ rem 1
width maxContent
```
> Add size constants and properties for grid areas

- spec/Clay/PositionSpec.hs
- src/Clay/Common.hs
- src/Clay/Display.hs
As detailed in https://caniuse.com/#feat=css-sticky,
Apple browsers require the -webkit- prefix to render the
sticky attribute.
This PR causes the attribute to render as:
```
position: -webkit-sticky;
position: sticky;
```
closes https://github.com/sebastiaanvisser/clay/issues/202
> Add -webkit- prefix to sticky position attribute

- clay.cabal
- spec/Clay/TransitionSpec.hs
- src/Clay/Transition.hs
(According to Chrome and w3schools.)
> Cubic bezier argument list should be comma separated

- CHANGELOG
- src/Clay/Media.hs
These are a couple of changes related to media queries:
* Adds the `all` media type.  A [reference](https://developer.mozilla.org/en-US/docs/Web/CSS/@media#media_types) mentions that media types other than `all`, `screen`, and `print` were deprecated, so documentation was updated to mention this fact.
* Adds support for the [`prefers-color-scheme`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) media feature.
I have also added a few documentation comments while making these changes.  If they were intentionally omitted for other functions, then I'd be happy to remove them.
> A couple of changes related to media queries

- spec/Clay/MediaSpec.hs
- src/Clay/Render.hs
I was bothered by the lack of tests, so I added some for this single module.  Adding more tests covering the entire library would be nice, but that was too ambitious to do in one go.
In the process, I noticed that there was a bug when rendering a key-only media feature such as `color`.  The syntax for Media Queries requires that media features always be surrounded by parentheses, but Clay omitted parentheses for these features.  So I also made a change to the `Clay.Render` module.
https://w3c.github.io/csswg-drafts/mediaqueries-5/#mq-syntax
> Add tests for the Clay.Media module

- spec/Clay/TextSpec.hs
- src/Clay/Text.hs
This adds support for the following CSS properties related to hyphenation:
*   [`hyphens`](https://developer.mozilla.org/en-US/docs/Web/CSS/hyphens)
*   [`hyphenate-character`](https://developer.mozilla.org/en-US/docs/Web/CSS/hyphenate-character)
*   [`hyphenate-limit-chars`](https://developer.mozilla.org/en-US/docs/Web/CSS/hyphenate-limit-chars)
> Add CSS properties related to hyphenation.

- clay.cabal
- examples/Main.hs
- spec/Clay/SizeSpec.hs
- src/Clay/Animation.hs
- src/Clay/Display.hs
- src/Clay/Filter.hs
- src/Clay/Property.hs
- src/Clay/Render.hs
- src/Clay/Size.hs
- src/Clay/Stylesheet.hs
- src/Clay/Transform.hs
- src/Clay/Transition.hs
Replace usage of 'Double' with 'Fixed E5' to avoid floating precision errors
> Replace usage of 'Double' with 'Fixed E5' to avoid floating precision errors

- spec/Clay/PseudoSpec.hs
- src/Clay/Pseudo.hs
- src/Clay/Render.hs
The `not` pseudo selector can only be applied to one argument at a time in most browsers, Safari seems to be the exception. The instance for `Not Refinement` allows you to apply `Not` to multiple arguments, however, there is no contaminator to combine two `Refinement` directly.
> Adds Not type class, Fixes #239

- spec/Clay/FlexboxSpec.hs
- src/Clay/Flexbox.hs
Also added tests for `justifyContent`.  Resolves https://github.com/sebastiaanvisser/clay/issues/247.
> Support `stretch` in `justify-content`.

- spec/Clay/GeometrySpec.hs
- src/Clay/Geometry.hs
This adds an `aspectRatio` function for generating the `aspect-ratio` CSS property and an `AspectRatio` type to represent aspect ratios.  To make the ratios feel more like [`Data.Ratio`](https://hackage.haskell.org/package/base-4.20.0.1/docs/Data-Ratio.html) ratios, this defines a `%` operator on two `Integer`s generating an `AspectRatio`.  So we could do things like this:
```haskell
aspectRatio (16%9)
aspectRatio auto
```
To allow for properties such as `aspect-ratio: auto 4/3`, we use a `withFallback` function to generate an `AspectRatio`:
```haskell
aspectRatio $ auto `withFallback` (16%9)
```
It is not legal to do something like `aspect-ratio: auto auto`.  While it would have been nice if we could have enforced this with types, this is hard, so it is enforced as a runtime error …
> Add support for `aspect-ratio` CSS property.

- CHANGELOG
- spec/Clay/GridSpec.hs
- spec/Clay/SizeSpec.hs
- spec/Common.hs
- src/Clay/Color.hs
- src/Clay/Grid.hs
- src/Clay/Text.hs
Hello,
Following our discussions in [issue 176](https://github.com/sebastiaanvisser/clay/issues/176), here is my pull request for Grid size and position support.
I've also performed some minor corrections to avoid GHC compiler warnings and compilation failures with older version of GHC.
Some notes:
- I've implemented a '//' operator for the CSS '/' operator. However, this operator is used in other CSS properties (background and font are the ones I know of). So, it's not fully coherent with the rest of the library. On the other hand, I find the syntax rather nice and natural (more than using tuples, especially because I already use them when a custom-ident is combined with an Integer).
- There are spaces between the the '/' and its parameters (1 / 2)  which is not removed when rendered in …
> Support for gride size and position
